### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by MarcusWichelmann** [ajnewlands/X11.Net#1]
Thank you for your great work!
What's the license of this code? Could you please add a LICENSE file to the repository?

**Comment by MarcusWichelmann** [comment]
Ah, there is one: https://github.com/ajnewlands/X11.Net/blob/master/X11/License.txt
Might make sense to move it to the repository root :)

**Comment by ajnewlands** [comment]
Yep, I went with a BSD license purely from the point of view of making usage as unrestricted as possible (short of just dumping it in the public domain, which I did consider).

**Comment by ajnewlands** [comment]
Moved, as suggested.
